
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://Xiaoshiz.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Xiaoshi Zhang"
title: "{ Purpose }"
description: "Blog and website of Xiaoshi Zhang, blogging mainly for science, photography and my daily life."
keywords: "Xiaoshi Zhang, personal, Science, Photography, Life"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/SanDiegoSunset.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 100
start-delay: 500
delete-delay: 1000
lines: # You can add HTML Tags in the Text
  - text: "Amy Yang shige keng"
  - text: "Welcome to Xiaoshi's personal website"

me-img: "/img/Profile Image.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 5

paginate: 5

linkedin-share: True
email-share: True
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "XiaoshiZ"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "June 2013"
    description: "Graduate from CUP!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "August 2013 - Today"
    description: "Studying in FSU"
  - image: "/img/intro-bg-l.jpg"
    date: "August 2013 - Today"
    description: "Studying in FSU"
# First image of the Timeline

timeline-img: "/img/头像.jpg"

###########
# Contact #
###########

email: "zxs19901004@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Xiaoshi Zhang is from China. He lives in Unitied Stated right now, pursing a doctoral degree in Chemical Engineering. In his spare time, Xiaoshi does all kinds of things that related to football."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "Linkedin-share"
    url: "https://www.linkedin.com/in/xiaoshi-zhang-a1b643b9/"
  - title: "github"
    url: "https://github.com/XiaoshiZ"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"


################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'
# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
